# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCodeOfConduct: true
AddContributionDocs: true
AddCopierCI: false
AddGitHubTemplates: true
AddMacToCI: false
AddPrecommit: true
AddWinToCI: false
AnswerStrategy: ask
Authors: Luisa Orozco <l.orozco@esciencecenter.nl>, Abel Soares Siqueira <abel.s.siqueira@gmail.com>
AutoIncludeTests: false
CodeOfConductContact: l.orozco@esciencecenter.nl
Indentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.6'
License: Apache-2.0
LicenseCopyrightHolders: Luisa Orozco, Abel Soares Siqueira
PackageName: MyModule
PackageOwner: luisaforozco
PackageUUID: d18defe2-ea8b-5af7-8ee9-e42adac5e2de
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.10.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
